name = "gorani-telegram-notifications"
main = "src/index.ts"
compatibility_date = "2026-05-27"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "GORANI_NOTIFICATIONS_KV"
id = "67539d57b6d8430ebe5a34f5cfec28d2"
